### ISSUE TITLE
Add basic packaging and install files

### ISSUE THREAD

**Issue by m3nu** [invoice-x/invoicex-gui#1]
I tried to run this but there was no help on installing it whatsoever:

- no `requirements.txt`
- no `setup.py`
- no hint in the README.
- no mention of any external dependencies.

**Comment by duskybomb** [comment]
The basic packages are there in [releases](https://github.com/invoice-x/invoicex-gui/releases).
And I will add the above mentioned things

**Comment by m3nu** [comment]
Still not clear how you made those packages and which extra files or commands are needed.

**Comment by m3nu** [comment]
The Mac release is not usable. It's a folder of different files. Can't be run.

<img width="250" alt="screen shot 2018-07-03 at 14 32 19" src="https://user-images.githubusercontent.com/3916435/42202439-03fcab18-7ece-11e8-9ec2-025ab29185af.png">

**Comment by m3nu** [comment]
Windows also doesn't work.

<img width="875" alt="screen shot 2018-07-03 at 14 34 09" src="https://user-images.githubusercontent.com/3916435/42202508-40233f44-7ece-11e8-9cd5-743fe0177343.png">

**Comment by duskybomb** [comment]
For now you can try by building it using `setup.py`
Let me check windows and mac problem

**Comment by duskybomb** [comment]
About Windows package, I think you are using Windows XP and Qt doesn't support XP anymore [link](https://doc.qt.io/qt-5/supported-platforms.html).
MacOS: Did you run `invoice-x` file?

**Comment by m3nu** [comment]
I don't have any other Windows version. This is an old VMWare image.

Then kindly add proper install- and requirements files so I can at least run it directly, if the packaging and releasing doesn't work yet.

**Comment by duskybomb** [comment]
I have added `requirements.txt` and `setup.py`

**Comment by m3nu** [comment]
I can run it using your requirements file. Your instructions are still conflicting since the first line installs it as package (not tested) and the second one runs it locally. It should be either-or. For dev you will use  the latter, later the former. This shouldn't be mixed.

```
$ python setup.py install
$ python main.py
```

Saving and most other functions cause a crash. I guess there is some work left to stabilize it. Interface in total looks clean.

Why not edit the fields on the right side instead of the dialog?

Data entered in the dialog is saved even after pressing **Discard**.

**Comment by duskybomb** [comment]
The crashes and Data being saved even after pressing Discard are on Mac?
Edit fields is in dialog, because I think we don't want accidental updates to field values.

**Comment by duskybomb** [comment]
A separate dialog to edit fields has another advantage, user can check what the original values are and can compare what he has edited.
